import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title> LNAddy.com </title>{' '}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>{' '}
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://lnaddy.com"> LNAddy.com! </a>{' '}
        </h1>{' '}
        <p className={styles.description}>
          A Lightning Address Server {' '}
        </p>{' '}

        <div className={styles.grid}>
          <a href="https://lightningaddress.com/" className={styles.card}>
            <h2> What&apos;s a Lightning Address? </h2>{' '}
            <p> Find in-depth information about the Lightning Address protocol. </p>{' '}
          </a>{' '}
          <a href="https://telegra.ph/lnurl-a-protocol-for-seamless-interaction-between-services-and-Lightning-wallets-08-19" className={styles.card}>
            <h2> What is the LNURL protocol?</h2>{' '}
            <p> Learn about the LNURL and how its used in self-hosted and wallet applications. </p>{' '}
          </a>{' '}
        </div>{' '}
      </main>{' '}
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />{' '}
          </span>{' '}
        </a>{' '}
      </footer>{' '}
    </div>
  )
}
